# Generated by Django 3.2 on 2023-05-26 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Bussiness', 'Bussiness'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=50, verbose_name='type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to=settings.AUTH_USER_MODEL, verbose_name='user phone')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Bussiness', 'Bussiness'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=50, verbose_name='type')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('region', models.CharField(max_length=50, verbose_name='region')),
                ('street', models.CharField(max_length=50, verbose_name='street')),
                ('note', models.TextField(blank=True, max_length=300, null=True, verbose_name='Note')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_city', to='settings.city', verbose_name='City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_country', to='settings.country', verbose_name='Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='user address')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Image')),
                ('code', models.CharField(default=utils.generator.generator, max_length=8, verbose_name='code')),
                ('code_used', models.BooleanField(default=False, verbose_name='Code Used')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
        ),
    ]
