# Generated by Django 3.2 on 2023-05-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Company')),
                ('logo', models.ImageField(upload_to='company', verbose_name='Logo')),
                ('about', models.TextField(blank=True, max_length=300, null=True, verbose_name='about')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Face Book')),
                ('tw_link', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('ins_link', models.URLField(blank=True, null=True, verbose_name='Instegram')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country Name')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_city', to='settings.country', verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
