# Generated by Django 3.2 on 2023-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Banner Title')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Baner Image')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
        ),
    ]
