# Generated by Django 3.2 on 2023-05-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utils.generator.generator, max_length=8, verbose_name='Code')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[('Horizontal', 'Horizontal'), ('Vertical', 'Vertical')], max_length=50, verbose_name='Orientation')),
                ('print_color', models.CharField(choices=[('Single-Side', 'Single-Side'), ('Double-Side', 'Double-Side')], max_length=50, verbose_name='Print Color')),
                ('side', models.CharField(choices=[('Single-Side', 'Single-Side'), ('Double-Side', 'Double-Side')], max_length=50, verbose_name='Side')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
                ('photo', models.ImageField(upload_to='Uploaded Photo', verbose_name='Uploaded Photo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderDetail', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderDetail_product', to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='Type')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_type', to='orders.order_detail', verbose_name='Order Detail Type')),
            ],
        ),
        migrations.CreateModel(
            name='Ordersize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='orders.order_detail', verbose_name='Order Detail Size')),
            ],
        ),
    ]
