# Generated by Django 3.2 on 2023-05-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
